name = "budget-manager"
main = "dist/_worker.js"
compatibility_date = "2025-10-31"
compatibility_flags = ["nodejs_compat"]

# KV namespace for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "857dec90311f4302a8bcbdad5d8f04df"
